# fly.toml app configuration file generated for nginx-blog on 2024-02-13T18:21:12+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nginx-blog'
primary_region = 'nrt'

[build]
  image = 'hyunsungjoo/nginx-blog:0.1.0'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
